name: Acquire Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload activation file
        uses: actions/upload-artifact@v2
        with:
          name: UnityActivationFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
