name: Unity PlayMode Tests
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'develop'
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ ( github.event_name == 'pull_request' || github.event.action == 'synchronize' ) }}

jobs:
  test:
    name: Run PlayMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Find Unity Project Version
        id: get-unity-version
        run: |
          PROJECT_PATH=$(find . -name ProjectSettings -type d -printf '%h\n' | head -1)
          echo "PROJECT_PATH=${PROJECT_PATH}" >> $GITHUB_ENV
          VERSION=$(grep -m 1 "m_EditorVersion:" ${PROJECT_PATH}/ProjectSettings/ProjectVersion.txt | cut -d' ' -f2)
          echo "UNITY_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Found Unity version: ${VERSION}"
      
      - name: Run PlayMode Tests in Unity Docker
        run: |
          docker run \
            --rm \
            -v "$(pwd):/github/workspace" \
            -e UNITY_LICENSE="1" \
            unityci/editor:ubuntu-$UNITY_VERSION-webgl \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile /dev/stdout \
            -projectPath /github/workspace/$PROJECT_PATH \
            -runTests \
            -testPlatform playmode \
            -testResults /github/workspace/TestResults/playmode-results.xml
        env:
          UNITY_VERSION: ${{ env.UNITY_VERSION }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode Test Results
          path: "TestResults"
          retention-days: 1
