name: Unity PlayMode Tests
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'develop'
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ ( github.event_name == 'pull_request' || github.event.action == 'synchronize' ) }}

jobs:
  test:
    name: Run PlayMode Tests
    runs-on: ubuntu-latest
    env:
      UNITY_PROJECT_PATH: ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Setup Unity (Auto-detect version)
        uses: buildalon/unity-setup@v1
        with:
          build-targets: 'Standalone' # Just needed for version detection
      
      - name: Activate Unity License
        uses: buildalon/activate-unity-license@v1
        with:
          license: 'Personal'
          username: '${{ secrets.UNITY_EMAIL }}'
          password: '${{ secrets.UNITY_PASSWORD }}'
      
      - name: Run PlayMode Tests
        uses: buildalon/unity-action@v1
        with:
          log-name: 'playmode-tests'
          args: '-quit -batchmode -runTests -testPlatform playmode -testResults ./playmode-test-results.xml'
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode Test Results
          path: |
            ./playmode-test-results.xml
            ${{ env.UNITY_PROJECT_PATH }}/**/*.log
          retention-days: 1
      
      - name: Cleanup Logs
        if: always()
        run: |
          find "${{ env.UNITY_PROJECT_PATH }}" -name "*.log" -type f -delete
